<?php

namespace CodersLabBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository {
    
    public function showBooksWhereIdIsBigger($id) {
        $em = $this->getEntityManager();
        
        $query = $em->createQuery("SELECT b FROM CodersLabBundle:Book b WHERE b.id > :id");
        $query->setParameter("id", $id);
        
        $books = $query->getResult();
        return $books;
    }
    
    public function showBooksWhereRatingIsBigger($rating) {
        $em = $this->getEntityManager();
        
        $query = $em->createQuery("SELECT b FROM CodersLabBundle:Book b WHERE b.rating > :rating");
        $query->setParameter("rating", $rating);
        
        $books = $query->getResult();
        return $books;
    }
    
    public function showBooksWhereTitleContains($string) {
        $em = $this->getEntityManager();
        
        $query = $em->createQuery("SELECT b FROM CodersLabBundle:Book b WHERE b.title LIKE :string");
        $query->setParameter("string", $string . "%");
        
        $books = $query->getResult();
        return $books;
    }
    // http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#other-expressions
}


